# 使用Ubuntu 24.04 作为基础镜像
FROM ubuntu:24.04 AS builder

# 阻止交互式提示
ARG DEBIAN_FRONTEND=noninteractive

# 设置工作目录
WORKDIR /env

# 更新系统并安装必要的构建工具和库
RUN apt-get update -y && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    curl \
    g++ \
    gcc \
    gdb \
    git \
    libicu-dev \
    libkrb5-dev \
    libssl-dev \
    libunwind8 \
    net-tools \
    openssl \
    unzip \
    zip \
    && rm -rf /var/lib/apt/lists/*

# 设置Boost版本号变量
ARG BOOST_VERSION=1_86_0

# 下载并构建Boost
RUN BOOST_VERSION_DOT=$(echo ${BOOST_VERSION} | sed 's/_/./g') \
    && curl -L https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION_DOT}/source/boost_${BOOST_VERSION}.tar.bz2 -o boost_${BOOST_VERSION}.tar.bz2 \
    && tar xjf boost_${BOOST_VERSION}.tar.bz2 \
    && rm boost_${BOOST_VERSION}.tar.bz2 \
    && mv boost_${BOOST_VERSION} boost \
    && cd boost \
    && ./bootstrap.sh \
    && ./b2 cxxflags=-fPIC \
    && cd ..

# 设置jemalloc版本号变量
ARG JEMALLOC_VERSION=5.3.0

# 下载并构建jemalloc
RUN curl -L https://github.com/jemalloc/jemalloc/releases/download/${JEMALLOC_VERSION}/jemalloc-${JEMALLOC_VERSION}.tar.bz2 -o jemalloc-${JEMALLOC_VERSION}.tar.bz2 \
    && tar xjf jemalloc-${JEMALLOC_VERSION}.tar.bz2 \
    && rm jemalloc-${JEMALLOC_VERSION}.tar.bz2 \
    && mv jemalloc-${JEMALLOC_VERSION} jemalloc \
    && cd jemalloc \
    && ./autogen.sh --with-jemalloc-prefix=je_ \
    && make -j$(nproc) \
    && cd ..

# 设置OpenSSL版本号变量
ARG OPENSSL_VERSION=3.3.2

# 下载并构建OpenSSL
RUN curl -L https://github.com/openssl/openssl/releases/download/openssl-${OPENSSL_VERSION}/openssl-${OPENSSL_VERSION}.tar.gz -o openssl-${OPENSSL_VERSION}.tar.gz \
    && tar zxvf openssl-${OPENSSL_VERSION}.tar.gz \
    && rm openssl-${OPENSSL_VERSION}.tar.gz \
    && mv openssl-${OPENSSL_VERSION} openssl \
    && cd openssl \
    && ./Configure \
    && make -j$(nproc) \
    && cd ..
