name: docker-env
on:
  workflow_dispatch:
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/openppp2
  BOOST_VERSION: 1_86_0  # 设置默认的Boost版本
  JEMALLOC_VERSION: 5.3.0 # 设置默认的Boost版本
  OPENSSL_VERSION: 3.3.2 # 设置默认的OpenSSL版本
  
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get version
        id: get_version
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT
        
      - name: Lowercase repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.env
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:env
            ghcr.io/${{ env.IMAGE_NAME }}:env
          build-args: | # 传递构建参数到Dockerfile
            BOOST_VERSION=${{ env.BOOST_VERSION }}
            JEMALLOC_VERSION=${{ env.JEMALLOC_VERSION }}
            OPENSSL_VERSION=${{ env.OPENSSL_VERSION }}
